"""add hash field

Revision ID: 8e26e31d2061
Revises: ca0697f956f8
Create Date: 2025-07-11 19:50:28.892774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e26e31d2061'
down_revision: Union[str, Sequence[str], None] = 'ca0697f956f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_results', sa.Column('task_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_results', 'task_hash')
    # ### end Alembic commands ###
